on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello

      - name: Get the output package name
        run: echo "${{ steps.hello.outputs.name }}"
